<a href="https://colab.research.google.com/github/JasmineVan/EnsembleLearning/blob/main/51800128_SVM_Ensemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras import layers
from tensorflow.keras import models
import numpy as np 

In [ ]:
import pandas as pd
dataframe = pd.read_csv("adult.data")
data = np.array(dataframe.values)
print(data.shape)
print(data[:3])

(32560, 15)
[[50 ' Self-emp-not-inc' 83311 ' Bachelors' 13 ' Married-civ-spouse'
  ' Exec-managerial' ' Husband' ' White' ' Male' 0 0 13 ' United-States'
  ' <=50K']
 [38 ' Private' 215646 ' HS-grad' 9 ' Divorced' ' Handlers-cleaners'
  ' Not-in-family' ' White' ' Male' 0 0 40 ' United-States' ' <=50K']
 [53 ' Private' 234721 ' 11th' 7 ' Married-civ-spouse'
  ' Handlers-cleaners' ' Husband' ' Black' ' Male' 0 0 40
  ' United-States' ' <=50K']]


In [ ]:
X = data[:,:-1]
#X = np.asarray(X.astype(np.float32))
y = data[:,-1]
print(X.shape)
print(y.shape)

(32560, 14)
(32560,)


In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for i in range(X.shape[1]):
    X[:,i] = encoder.fit_transform(X[:,i])
print(X)

[[33 6 2925 ... 0 12 39]
 [21 4 14085 ... 0 39 39]
 [36 4 15335 ... 0 39 39]
 ...
 [41 4 7882 ... 0 39 39]
 [5 4 12880 ... 0 19 39]
 [35 5 17824 ... 0 39 39]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)
print(y)

[0 0 0 ... 0 0 1]


In [ ]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()
X = minmax.fit_transform(X)

In [ ]:
from collections import Counter
counter = Counter()
counter.update(y)
print(counter)

Counter({0: 24719, 1: 7841})


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print('Train:')
print(X_train.shape)
print(y_train.shape)
print('Test:')
print(X_test.shape)
print(y_test.shape)

Train:
(22792, 14)
(22792,)
Test:
(9768, 14)
(9768,)


#Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred = clf.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91      7395
           1       0.75      0.63      0.68      2373

    accuracy                           0.86      9768
   macro avg       0.82      0.78      0.80      9768
weighted avg       0.85      0.86      0.85      9768



#Adaboost

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()
ada.fit(X_train, y_train)

AdaBoostClassifier()

In [ ]:
y_pred = ada.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.94      0.91      7395
           1       0.76      0.61      0.68      2373

    accuracy                           0.86      9768
   macro avg       0.82      0.78      0.79      9768
weighted avg       0.85      0.86      0.85      9768



#SVM

In [ ]:
from sklearn import svm
model = svm.SVC(kernel='poly', C=2)
model.fit(X_train, y_train)

SVC(C=2, kernel='poly')

In [ ]:
y_pred = model.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.94      0.90      7395
           1       0.74      0.56      0.64      2373

    accuracy                           0.85      9768
   macro avg       0.81      0.75      0.77      9768
weighted avg       0.84      0.85      0.84      9768

